use rustify_ir::{
    BinaryOperator, Expression, ExpressionKind, Program, Statement, StringMethod, StringTransform,
    Type, UnaryOperator,
};
use std::fmt::Write;
use thiserror::Error;

#[derive(Debug, Error)]
pub enum CodegenError {
    #[error("invalid structured IR: {0}")]
    InvalidIr(String),
}

pub fn emit(program: &Program) -> Result<String, CodegenError> {
    let mut output = String::from("// Generated by Rustify. Do not edit manually.\n\n");
    for structure in &program.structs {
        writeln!(output, "#[derive(Clone, Debug, PartialEq)]").unwrap();
        writeln!(
            output,
            "pub struct {} {{",
            rust_type_identifier(&structure.name)
        )
        .unwrap();
        for field in &structure.fields {
            writeln!(
                output,
                "    pub {}: {},",
                rust_identifier(&field.name),
                emit_type(&field.ty)
            )
            .unwrap();
        }
        writeln!(output, "}}\n").unwrap();
    }
    for enumeration in &program.enums {
        writeln!(output, "#[derive(Clone, Debug, PartialEq)]").unwrap();
        writeln!(
            output,
            "pub enum {} {{",
            rust_type_identifier(&enumeration.name)
        )
        .unwrap();
        for variant in &enumeration.variants {
            writeln!(output, "    {},", rust_type_identifier(variant)).unwrap();
        }
        writeln!(output, "}}\n").unwrap();
    }
    for function in &program.functions {
        write!(
            output,
            "pub {}fn {}(",
            if function.is_async { "async " } else { "" },
            rust_identifier(&function.name)
        )
        .unwrap();
        for (index, parameter) in function.params.iter().enumerate() {
            if index > 0 {
                output.push_str(", ");
            }
            write!(
                output,
                "{}: {}",
                rust_identifier(&parameter.name),
                emit_type(&parameter.ty)
            )
            .unwrap();
        }
        if function.return_type == Type::Unit {
            writeln!(output, ") {{").unwrap();
        } else {
            writeln!(output, ") -> {} {{", emit_type(&function.return_type)).unwrap();
        }

        for parameter in &function.params {
            if !statements_use_identifier(&function.body, &parameter.name) {
                writeln!(output, "    let _ = &{};", rust_identifier(&parameter.name)).unwrap();
            }
        }

        emit_statements(&mut output, &function.body, 1)?;
        writeln!(output, "}}\n").unwrap();
    }
    Ok(output)
}

pub fn uses_runtime(program: &Program) -> bool {
    program
        .structs
        .iter()
        .flat_map(|structure| structure.fields.iter())
        .any(|field| type_uses_runtime(&field.ty))
        || program.functions.iter().any(|function| {
            type_uses_runtime(&function.return_type)
                || function
                    .params
                    .iter()
                    .any(|parameter| type_uses_runtime(&parameter.ty))
                || statements_use_runtime(&function.body)
        })
}

fn type_uses_runtime(ty: &Type) -> bool {
    match ty {
        Type::JsonValue => true,
        Type::Vec(inner) | Type::Option(inner) | Type::Promise(inner) => type_uses_runtime(inner),
        Type::Result(ok, error) => type_uses_runtime(ok) || type_uses_runtime(error),
        _ => false,
    }
}

fn statements_use_runtime(statements: &[Statement]) -> bool {
    statements.iter().any(|statement| match statement {
        Statement::Variable { value, .. }
        | Statement::Assignment { value, .. }
        | Statement::Return(value)
        | Statement::Expression(value) => expression_uses_runtime(value),
        Statement::ConsoleLog(values) => values.iter().any(expression_uses_runtime),
        Statement::If {
            condition,
            then_body,
            else_body,
        } => {
            expression_uses_runtime(condition)
                || statements_use_runtime(then_body)
                || statements_use_runtime(else_body)
        }
        Statement::While { condition, body } => {
            expression_uses_runtime(condition) || statements_use_runtime(body)
        }
        Statement::ForOf { iterable, body, .. } => {
            expression_uses_runtime(iterable) || statements_use_runtime(body)
        }
        Statement::ReturnVoid | Statement::Break | Statement::Continue => false,
    })
}

fn statements_use_identifier(statements: &[Statement], name: &str) -> bool {
    for statement in statements {
        if statement_uses_identifier(statement, name) {
            return true;
        }

        if matches!(statement, Statement::Variable { name: binding, .. } if binding == name) {
            return false;
        }

        if statement_definitely_exits(statement) {
            return false;
        }
    }

    false
}

fn statement_uses_identifier(statement: &Statement, name: &str) -> bool {
    match statement {
        Statement::Variable { value, .. }
        | Statement::Assignment { value, .. }
        | Statement::Return(value)
        | Statement::Expression(value) => expression_uses_identifier(value, name),
        Statement::ConsoleLog(values) => values
            .iter()
            .any(|value| expression_uses_identifier(value, name)),
        Statement::If {
            condition,
            then_body,
            else_body,
        } => {
            expression_uses_identifier(condition, name)
                || statements_use_identifier(then_body, name)
                || statements_use_identifier(else_body, name)
        }
        Statement::While { condition, body } => {
            expression_uses_identifier(condition, name) || statements_use_identifier(body, name)
        }
        Statement::ForOf {
            binding,
            iterable,
            body,
        } => {
            expression_uses_identifier(iterable, name)
                || (binding != name && statements_use_identifier(body, name))
        }
        Statement::ReturnVoid | Statement::Break | Statement::Continue => false,
    }
}

fn statements_mutate_identifier(statements: &[Statement], name: &str) -> bool {
    for statement in statements {
        if statement_mutates_identifier(statement, name) {
            return true;
        }

        if matches!(statement, Statement::Variable { name: binding, .. } if binding == name) {
            return false;
        }

        if statement_definitely_exits(statement) {
            return false;
        }
    }

    false
}

fn statement_definitely_exits(statement: &Statement) -> bool {
    match statement {
        Statement::Return(_) | Statement::ReturnVoid | Statement::Break | Statement::Continue => {
            true
        }
        Statement::If {
            then_body,
            else_body,
            ..
        } => {
            !else_body.is_empty()
                && then_body.last().is_some_and(statement_definitely_exits)
                && else_body.last().is_some_and(statement_definitely_exits)
        }
        _ => false,
    }
}

fn statement_mutates_identifier(statement: &Statement, name: &str) -> bool {
    match statement {
        Statement::Assignment {
            name: assignment,
            value,
        } => assignment == name || expression_mutates_identifier(value, name),
        Statement::Variable { value, .. }
        | Statement::Return(value)
        | Statement::Expression(value) => expression_mutates_identifier(value, name),
        Statement::ConsoleLog(values) => values
            .iter()
            .any(|value| expression_mutates_identifier(value, name)),
        Statement::If {
            condition,
            then_body,
            else_body,
        } => {
            expression_mutates_identifier(condition, name)
                || statements_mutate_identifier(then_body, name)
                || statements_mutate_identifier(else_body, name)
        }
        Statement::While { condition, body } => {
            expression_mutates_identifier(condition, name)
                || statements_mutate_identifier(body, name)
        }
        Statement::ForOf {
            binding,
            iterable,
            body,
        } => {
            expression_mutates_identifier(iterable, name)
                || (binding != name && statements_mutate_identifier(body, name))
        }
        Statement::ReturnVoid | Statement::Break | Statement::Continue => false,
    }
}

fn expression_mutates_identifier(expression: &Expression, name: &str) -> bool {
    match &expression.kind {
        ExpressionKind::ArrayPush { array, value } => {
            matches!(&array.kind, ExpressionKind::Identifier(identifier) if identifier == name)
                || expression_mutates_identifier(value, name)
        }
        ExpressionKind::ArrayPop(array) => {
            matches!(&array.kind, ExpressionKind::Identifier(identifier) if identifier == name)
        }
        ExpressionKind::Some(value)
        | ExpressionKind::Await(value)
        | ExpressionKind::ArrayLength(value)
        | ExpressionKind::OptionCheck { value, .. }
        | ExpressionKind::ResultCheck { value, .. }
        | ExpressionKind::StringTransform {
            receiver: value, ..
        }
        | ExpressionKind::Property { object: value, .. }
        | ExpressionKind::Unary { value, .. } => expression_mutates_identifier(value, name),
        ExpressionKind::ArrayIncludes { array, value } => {
            expression_mutates_identifier(array, name) || expression_mutates_identifier(value, name)
        }
        ExpressionKind::ArrayGet { array, index } => {
            expression_mutates_identifier(array, name) || expression_mutates_identifier(index, name)
        }
        ExpressionKind::ArrayJoin { array, separator } => {
            expression_mutates_identifier(array, name)
                || expression_mutates_identifier(separator, name)
        }
        ExpressionKind::OptionUnwrapOr { value, fallback }
        | ExpressionKind::ResultUnwrapOr { value, fallback } => {
            expression_mutates_identifier(value, name)
                || expression_mutates_identifier(fallback, name)
        }
        ExpressionKind::StringMethod {
            receiver, argument, ..
        } => {
            expression_mutates_identifier(receiver, name)
                || expression_mutates_identifier(argument, name)
        }
        ExpressionKind::Array(values) => values
            .iter()
            .any(|value| expression_mutates_identifier(value, name)),
        ExpressionKind::StructLiteral { fields, .. } => fields
            .iter()
            .any(|(_, value)| expression_mutates_identifier(value, name)),
        ExpressionKind::Call { arguments, .. } => arguments
            .iter()
            .any(|value| expression_mutates_identifier(value, name)),
        ExpressionKind::Binary { left, right, .. } => {
            expression_mutates_identifier(left, name) || expression_mutates_identifier(right, name)
        }
        ExpressionKind::Conditional {
            condition,
            then_value,
            else_value,
        } => {
            expression_mutates_identifier(condition, name)
                || expression_mutates_identifier(then_value, name)
                || expression_mutates_identifier(else_value, name)
        }
        ExpressionKind::Template { expressions, .. } => expressions
            .iter()
            .any(|value| expression_mutates_identifier(value, name)),
        ExpressionKind::String(_)
        | ExpressionKind::Number(_)
        | ExpressionKind::Boolean(_)
        | ExpressionKind::Null
        | ExpressionKind::Identifier(_)
        | ExpressionKind::EnumVariant { .. } => false,
    }
}

fn expression_uses_identifier(expression: &Expression, name: &str) -> bool {
    match &expression.kind {
        ExpressionKind::Identifier(identifier) => identifier == name,
        ExpressionKind::Some(value)
        | ExpressionKind::Await(value)
        | ExpressionKind::ArrayLength(value)
        | ExpressionKind::ArrayPop(value)
        | ExpressionKind::OptionCheck { value, .. }
        | ExpressionKind::ResultCheck { value, .. }
        | ExpressionKind::StringTransform {
            receiver: value, ..
        }
        | ExpressionKind::Property { object: value, .. }
        | ExpressionKind::Unary { value, .. } => expression_uses_identifier(value, name),
        ExpressionKind::ArrayIncludes { array, value }
        | ExpressionKind::ArrayPush { array, value } => {
            expression_uses_identifier(array, name) || expression_uses_identifier(value, name)
        }
        ExpressionKind::ArrayGet { array, index } => {
            expression_uses_identifier(array, name) || expression_uses_identifier(index, name)
        }
        ExpressionKind::ArrayJoin { array, separator } => {
            expression_uses_identifier(array, name) || expression_uses_identifier(separator, name)
        }
        ExpressionKind::OptionUnwrapOr { value, fallback }
        | ExpressionKind::ResultUnwrapOr { value, fallback } => {
            expression_uses_identifier(value, name) || expression_uses_identifier(fallback, name)
        }
        ExpressionKind::StringMethod {
            receiver, argument, ..
        } => {
            expression_uses_identifier(receiver, name) || expression_uses_identifier(argument, name)
        }
        ExpressionKind::Array(values) => values
            .iter()
            .any(|value| expression_uses_identifier(value, name)),
        ExpressionKind::StructLiteral { fields, .. } => fields
            .iter()
            .any(|(_, value)| expression_uses_identifier(value, name)),
        ExpressionKind::Call { arguments, .. } => arguments
            .iter()
            .any(|value| expression_uses_identifier(value, name)),
        ExpressionKind::Binary { left, right, .. } => {
            expression_uses_identifier(left, name) || expression_uses_identifier(right, name)
        }
        ExpressionKind::Conditional {
            condition,
            then_value,
            else_value,
        } => {
            expression_uses_identifier(condition, name)
                || expression_uses_identifier(then_value, name)
                || expression_uses_identifier(else_value, name)
        }
        ExpressionKind::Template { expressions, .. } => expressions
            .iter()
            .any(|value| expression_uses_identifier(value, name)),
        ExpressionKind::String(_)
        | ExpressionKind::Number(_)
        | ExpressionKind::Boolean(_)
        | ExpressionKind::Null
        | ExpressionKind::EnumVariant { .. } => false,
    }
}

fn expression_uses_runtime(expression: &Expression) -> bool {
    type_uses_runtime(&expression.ty)
        || match &expression.kind {
            ExpressionKind::Call { callee, arguments } => {
                callee.starts_with("JSON.")
                    || callee.starts_with("Rustify.")
                    || arguments.iter().any(expression_uses_runtime)
            }
            ExpressionKind::Some(value)
            | ExpressionKind::Await(value)
            | ExpressionKind::ArrayLength(value)
            | ExpressionKind::Property { object: value, .. } => expression_uses_runtime(value),
            ExpressionKind::ArrayIncludes { array, value } => {
                expression_uses_runtime(array) || expression_uses_runtime(value)
            }
            ExpressionKind::ArrayPush { array, value } => {
                expression_uses_runtime(array) || expression_uses_runtime(value)
            }
            ExpressionKind::ArrayPop(array) => expression_uses_runtime(array),
            ExpressionKind::ArrayGet { array, index } => {
                expression_uses_runtime(array) || expression_uses_runtime(index)
            }
            ExpressionKind::ArrayJoin { array, separator } => {
                expression_uses_runtime(array) || expression_uses_runtime(separator)
            }
            ExpressionKind::OptionCheck { value, .. } => expression_uses_runtime(value),
            ExpressionKind::OptionUnwrapOr { value, fallback } => {
                expression_uses_runtime(value) || expression_uses_runtime(fallback)
            }
            ExpressionKind::ResultCheck { value, .. } => expression_uses_runtime(value),
            ExpressionKind::ResultUnwrapOr { value, fallback } => {
                expression_uses_runtime(value) || expression_uses_runtime(fallback)
            }
            ExpressionKind::StringMethod {
                receiver, argument, ..
            } => expression_uses_runtime(receiver) || expression_uses_runtime(argument),
            ExpressionKind::StringTransform { receiver, .. } => expression_uses_runtime(receiver),
            ExpressionKind::Array(values) => values.iter().any(expression_uses_runtime),
            ExpressionKind::StructLiteral { fields, .. } => fields
                .iter()
                .any(|(_, value)| expression_uses_runtime(value)),
            ExpressionKind::Binary { left, right, .. } => {
                expression_uses_runtime(left) || expression_uses_runtime(right)
            }
            ExpressionKind::Unary { value, .. } => expression_uses_runtime(value),
            ExpressionKind::Conditional {
                condition,
                then_value,
                else_value,
            } => {
                expression_uses_runtime(condition)
                    || expression_uses_runtime(then_value)
                    || expression_uses_runtime(else_value)
            }
            ExpressionKind::Template { expressions, .. } => {
                expressions.iter().any(expression_uses_runtime)
            }
            _ => false,
        }
}

pub fn explain(program: &Program) -> String {
    let mut output = String::new();
    for structure in &program.structs {
        writeln!(output, "type {} -> Rust struct", structure.name).unwrap();
    }
    for enumeration in &program.enums {
        writeln!(output, "enum {} -> Rust enum", enumeration.name).unwrap();
    }
    for function in &program.functions {
        let params = function
            .params
            .iter()
            .map(|param| format!("{}: {}", rust_identifier(&param.name), emit_type(&param.ty)))
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(
            output,
            "{}function {} -> pub {}fn {}({}) -> {} ({} statement(s))",
            if function.is_async { "async " } else { "" },
            function.name,
            if function.is_async { "async " } else { "" },
            rust_identifier(&function.name),
            params,
            emit_type(&function.return_type),
            function.body.len()
        )
        .unwrap();
        explain_statements(&mut output, &function.body, 1);
    }
    output
}

fn explain_statements(output: &mut String, statements: &[Statement], depth: usize) {
    let indent = "  ".repeat(depth);
    for statement in statements {
        let description = match statement {
            Statement::Variable {
                name,
                mutable,
                ty,
                value,
            } => format!(
                "{} variable `{name}: {}` from {}",
                if *mutable { "mutable" } else { "immutable" },
                emit_type(ty),
                explain_expression(value)
            ),
            Statement::Assignment { name, value } => {
                format!("assignment to `{name}` from {}", explain_expression(value))
            }
            Statement::Return(value) => format!(
                "return `{}` from {}",
                emit_type(&value.ty),
                explain_expression(value)
            ),
            Statement::ReturnVoid => "return void".to_owned(),
            Statement::Break => "break loop".to_owned(),
            Statement::Continue => "continue loop".to_owned(),
            Statement::Expression(value) => explain_expression(value),
            Statement::ConsoleLog(values) => {
                format!("console.log({} argument(s)) -> println!", values.len())
            }
            Statement::If { condition, .. } => {
                format!("if/else with {}", explain_expression(condition))
            }
            Statement::While { condition, .. } => {
                format!("while loop with {}", explain_expression(condition))
            }
            Statement::ForOf {
                binding, iterable, ..
            } => format!(
                "for...of -> Rust for binding `{binding}` over {}",
                explain_expression(iterable)
            ),
        };
        writeln!(output, "{indent}{description}").unwrap();
        match statement {
            Statement::If {
                then_body,
                else_body,
                ..
            } => {
                explain_statements(output, then_body, depth + 1);
                explain_statements(output, else_body, depth + 1);
            }
            Statement::While { body, .. } | Statement::ForOf { body, .. } => {
                explain_statements(output, body, depth + 1);
            }
            _ => {}
        }
    }
}

fn explain_expression(expression: &Expression) -> String {
    match &expression.kind {
        ExpressionKind::String(_) => "string literal -> String".to_owned(),
        ExpressionKind::Number(_) => "number literal -> f64".to_owned(),
        ExpressionKind::Boolean(_) => "boolean literal -> bool".to_owned(),
        ExpressionKind::Null => format!("null -> {}", emit_type(&expression.ty)),
        ExpressionKind::Some(value) => {
            format!("nullable value -> Some({})", explain_expression(value))
        }
        ExpressionKind::Await(value) => {
            format!("await -> Rust .await on {}", explain_expression(value))
        }
        ExpressionKind::Identifier(name) => format!("identifier `{name}`"),
        ExpressionKind::Array(values) => {
            format!("array literal -> Vec with {} element(s)", values.len())
        }
        ExpressionKind::StructLiteral { name, .. } => format!("object literal -> `{name}` struct"),
        ExpressionKind::Call { callee, .. } => {
            format!("call `{callee}` -> `{}`", rust_callee(callee))
        }
        ExpressionKind::Property { property, .. } => format!(
            "property access -> Rust field `{}`{}",
            rust_identifier(property),
            if type_is_copy(&expression.ty) {
                ""
            } else {
                " cloned to preserve reusable TypeScript access"
            }
        ),
        ExpressionKind::ArrayLength(_) => "array.length -> Vec::len() as f64".to_owned(),
        ExpressionKind::ArrayIncludes { .. } => "array.includes -> Vec::contains".to_owned(),
        ExpressionKind::ArrayPush { .. } => "array.push -> Vec::push".to_owned(),
        ExpressionKind::ArrayPop(_) => "array.pop -> Vec::pop returning Option<T>".to_owned(),
        ExpressionKind::ArrayGet { .. } => {
            "array[index] -> checked Vec::get(index).cloned() returning Option<T>".to_owned()
        }
        ExpressionKind::ArrayJoin { .. } => "array.join -> Vec<String>::join".to_owned(),
        ExpressionKind::OptionCheck { is_some, .. } => format!(
            "optional check -> Option::{}",
            if *is_some { "is_some" } else { "is_none" }
        ),
        ExpressionKind::OptionUnwrapOr { .. } => {
            "optional fallback -> Option::unwrap_or without panic".to_owned()
        }
        ExpressionKind::ResultCheck { is_ok, .. } => format!(
            "result check -> Result::{}",
            if *is_ok { "is_ok" } else { "is_err" }
        ),
        ExpressionKind::ResultUnwrapOr { .. } => {
            "result fallback -> Result::unwrap_or without panic".to_owned()
        }
        ExpressionKind::StringMethod { method, .. } => format!(
            "string method -> String::{}",
            match method {
                StringMethod::Includes => "contains",
                StringMethod::StartsWith => "starts_with",
                StringMethod::EndsWith => "ends_with",
            }
        ),
        ExpressionKind::StringTransform { transform, .. } => format!(
            "string transform -> String::{}",
            match transform {
                StringTransform::Trim => "trim",
                StringTransform::ToUpperCase => "to_uppercase",
                StringTransform::ToLowerCase => "to_lowercase",
            }
        ),
        ExpressionKind::EnumVariant {
            enumeration,
            variant,
        } => format!("enum variant -> {enumeration}::{variant}"),
        ExpressionKind::Binary { operator, .. } => {
            format!("binary operation `{}`", emit_operator(*operator))
        }
        ExpressionKind::Unary { operator, .. } => format!(
            "unary operation `{}`",
            match operator {
                UnaryOperator::Not => "!",
                UnaryOperator::Negate => "-",
            }
        ),
        ExpressionKind::Conditional { .. } => "conditional expression -> Rust if/else".to_owned(),
        ExpressionKind::Template { .. } => "template literal -> format!".to_owned(),
    }
}

pub fn emit_type(ty: &Type) -> String {
    match ty {
        Type::String => "String".to_owned(),
        Type::F64 => "f64".to_owned(),
        Type::Bool => "bool".to_owned(),
        Type::Unit => "()".to_owned(),
        Type::JsonValue => "rustify_runtime::JsonValue".to_owned(),
        Type::Named(name) => rust_type_identifier(name),
        Type::Vec(inner) => format!("Vec<{}>", emit_type(inner)),
        Type::Option(inner) => format!("Option<{}>", emit_type(inner)),
        Type::Result(ok, error) => format!("Result<{}, {}>", emit_type(ok), emit_type(error)),
        Type::Promise(inner) => format!("impl std::future::Future<Output = {}>", emit_type(inner)),
    }
}

fn type_is_copy(ty: &Type) -> bool {
    matches!(ty, Type::F64 | Type::Bool | Type::Unit)
}

fn type_requires_clone(ty: &Type) -> bool {
    !type_is_copy(ty) && !matches!(ty, Type::Promise(_))
}

fn type_is_must_use(ty: &Type) -> bool {
    matches!(ty, Type::Option(_) | Type::Result(_, _))
}

fn emit_mutable_receiver(expression: &Expression) -> Result<String, CodegenError> {
    match &expression.kind {
        ExpressionKind::Identifier(name) => Ok(rust_identifier(name)),
        _ => Err(CodegenError::InvalidIr(
            "array mutation receiver must be a local binding".to_owned(),
        )),
    }
}

fn emit_borrow_source(expression: &Expression) -> Result<String, CodegenError> {
    match &expression.kind {
        ExpressionKind::Identifier(name) => Ok(rust_identifier(name)),
        ExpressionKind::Property { object, property } => Ok(format!(
            "{}.{}",
            emit_borrow_source(object)?,
            rust_identifier(property)
        )),
        _ => emit_expression(expression),
    }
}

fn emit_statements(
    output: &mut String,
    statements: &[Statement],
    depth: usize,
) -> Result<(), CodegenError> {
    for (index, statement) in statements.iter().enumerate() {
        emit_statement(output, statement, &statements[index + 1..], depth)?;
        if statement_definitely_exits(statement) {
            break;
        }
    }
    Ok(())
}

fn emit_statement(
    output: &mut String,
    statement: &Statement,
    following: &[Statement],
    depth: usize,
) -> Result<(), CodegenError> {
    let indent = "    ".repeat(depth);
    match statement {
        Statement::Variable {
            name,
            mutable,
            ty,
            value,
        } => writeln!(
            output,
            "{indent}let {}{}: {} = {};",
            if *mutable && statements_mutate_identifier(following, name) {
                "mut "
            } else {
                ""
            },
            rust_identifier(name),
            emit_type(ty),
            emit_expression(value)?
        )
        .and_then(|_| writeln!(output, "{indent}let _ = &{};", rust_identifier(name)))
        .unwrap(),
        Statement::Assignment { name, value } => writeln!(
            output,
            "{indent}{} = {};",
            rust_identifier(name),
            emit_expression(value)?
        )
        .and_then(|_| writeln!(output, "{indent}let _ = &{};", rust_identifier(name)))
        .unwrap(),
        Statement::Return(value) => {
            writeln!(output, "{indent}return {};", emit_expression(value)?).unwrap()
        }
        Statement::ReturnVoid => writeln!(output, "{indent}return;").unwrap(),
        Statement::Break => writeln!(output, "{indent}break;").unwrap(),
        Statement::Continue => writeln!(output, "{indent}continue;").unwrap(),
        Statement::Expression(value) if type_is_must_use(&value.ty) => {
            writeln!(output, "{indent}let _ = {};", emit_expression(value)?).unwrap()
        }
        Statement::Expression(value) => {
            writeln!(output, "{indent}{};", emit_expression(value)?).unwrap()
        }
        Statement::ConsoleLog(values) => {
            if values.is_empty() {
                writeln!(output, "{indent}println!();").unwrap();
            } else {
                let format = values
                    .iter()
                    .map(|value| {
                        if matches!(value.kind, ExpressionKind::Template { .. }) {
                            "{}"
                        } else {
                            "{:?}"
                        }
                    })
                    .collect::<Vec<_>>()
                    .join(" ");
                let arguments = values
                    .iter()
                    .map(emit_borrow_source)
                    .collect::<Result<Vec<_>, _>>()?
                    .join(", ");
                writeln!(output, "{indent}println!(\"{format}\", {arguments});").unwrap();
            }
        }
        Statement::If {
            condition,
            then_body,
            else_body,
        } => {
            writeln!(output, "{indent}if {} {{", emit_expression(condition)?).unwrap();
            emit_statements(output, then_body, depth + 1)?;
            if else_body.is_empty() {
                writeln!(output, "{indent}}}").unwrap();
            } else {
                writeln!(output, "{indent}}} else {{").unwrap();
                emit_statements(output, else_body, depth + 1)?;
                writeln!(output, "{indent}}}").unwrap();
            }
        }
        Statement::While { condition, body } => {
            writeln!(output, "{indent}while {} {{", emit_expression(condition)?).unwrap();
            emit_statements(output, body, depth + 1)?;
            writeln!(output, "{indent}}}").unwrap();
        }
        Statement::ForOf {
            binding,
            iterable,
            body,
        } => {
            writeln!(
                output,
                "{indent}for {} in {} {{",
                rust_identifier(binding),
                emit_expression(iterable)?
            )
            .unwrap();
            if !statements_use_identifier(body, binding) {
                writeln!(output, "{indent}    let _ = &{};", rust_identifier(binding)).unwrap();
            }
            emit_statements(output, body, depth + 1)?;
            writeln!(output, "{indent}}}").unwrap();
        }
    }
    Ok(())
}

fn emit_expression(expression: &Expression) -> Result<String, CodegenError> {
    emit_expression_with_precedence(expression, 0)
}

fn emit_expression_with_precedence(
    expression: &Expression,
    parent_precedence: u8,
) -> Result<String, CodegenError> {
    Ok(match &expression.kind {
        ExpressionKind::String(value) => format!("{value:?}.to_string()"),
        ExpressionKind::Number(value) => {
            if value.fract() == 0.0 {
                format!("{value:.1}")
            } else {
                value.to_string()
            }
        }
        ExpressionKind::Boolean(value) => value.to_string(),
        ExpressionKind::Null => "None".to_owned(),
        ExpressionKind::Some(value) => format!("Some({})", emit_expression(value)?),
        ExpressionKind::Await(value) => format!("{}.await", emit_expression(value)?),
        ExpressionKind::Identifier(name) => {
            let identifier = rust_identifier(name);
            if type_requires_clone(&expression.ty) {
                format!("{identifier}.clone()")
            } else {
                identifier
            }
        }
        ExpressionKind::Array(values) => format!(
            "vec![{}]",
            values
                .iter()
                .map(emit_expression)
                .collect::<Result<Vec<_>, _>>()?
                .join(", ")
        ),
        ExpressionKind::StructLiteral { name, fields } => format!(
            "{} {{ {} }}",
            rust_type_identifier(name),
            fields
                .iter()
                .map(|(field, value)| {
                    Ok(format!(
                        "{}: {}",
                        rust_identifier(field),
                        emit_expression(value)?
                    ))
                })
                .collect::<Result<Vec<_>, CodegenError>>()?
                .join(", ")
        ),
        ExpressionKind::Call { callee, arguments } => format!(
            "{}({})",
            rust_callee(callee),
            arguments
                .iter()
                .map(emit_expression)
                .collect::<Result<Vec<_>, _>>()?
                .join(", ")
        ),
        ExpressionKind::Property { object, property } => {
            let access = format!(
                "{}.{}",
                emit_borrow_source(object)?,
                rust_identifier(property)
            );
            if type_is_copy(&expression.ty) {
                access
            } else {
                format!("{access}.clone()")
            }
        }
        ExpressionKind::ArrayLength(value) => {
            format!("{}.len() as f64", emit_borrow_source(value)?)
        }
        ExpressionKind::ArrayIncludes { array, value } => {
            format!(
                "{}.contains(&{})",
                emit_borrow_source(array)?,
                emit_borrow_source(value)?
            )
        }
        ExpressionKind::ArrayPush { array, value } => {
            format!(
                "{}.push({})",
                emit_mutable_receiver(array)?,
                emit_expression(value)?
            )
        }
        ExpressionKind::ArrayPop(array) => format!("{}.pop()", emit_mutable_receiver(array)?),
        ExpressionKind::ArrayGet { array, index } => format!(
            "{{ let rustify_array_ref = &{}; let rustify_index_value: f64 = {}; \
             if rustify_index_value >= 0.0 && rustify_index_value.fract() == 0.0 {{ \
             rustify_array_ref.get(rustify_index_value as usize).cloned() }} else {{ None }} }}",
            emit_borrow_source(array)?,
            emit_expression(index)?
        ),
        ExpressionKind::ArrayJoin { array, separator } => format!(
            "{}.join({}.as_str())",
            emit_borrow_source(array)?,
            emit_borrow_source(separator)?
        ),
        ExpressionKind::OptionCheck { value, is_some } => format!(
            "{}.{}()",
            emit_borrow_source(value)?,
            if *is_some { "is_some" } else { "is_none" }
        ),
        ExpressionKind::OptionUnwrapOr { value, fallback } => format!(
            "{}.unwrap_or({})",
            emit_expression(value)?,
            emit_expression(fallback)?
        ),
        ExpressionKind::ResultCheck { value, is_ok } => format!(
            "{}.{}()",
            emit_borrow_source(value)?,
            if *is_ok { "is_ok" } else { "is_err" }
        ),
        ExpressionKind::ResultUnwrapOr { value, fallback } => format!(
            "{}.unwrap_or({})",
            emit_expression(value)?,
            emit_expression(fallback)?
        ),
        ExpressionKind::StringMethod {
            receiver,
            method,
            argument,
        } => format!(
            "{}.{}({}.as_str())",
            emit_borrow_source(receiver)?,
            match method {
                StringMethod::Includes => "contains",
                StringMethod::StartsWith => "starts_with",
                StringMethod::EndsWith => "ends_with",
            },
            emit_borrow_source(argument)?
        ),
        ExpressionKind::StringTransform {
            receiver,
            transform,
        } => match transform {
            StringTransform::Trim => {
                format!("{}.trim().to_string()", emit_borrow_source(receiver)?)
            }
            StringTransform::ToUpperCase => {
                format!("{}.to_uppercase()", emit_borrow_source(receiver)?)
            }
            StringTransform::ToLowerCase => {
                format!("{}.to_lowercase()", emit_borrow_source(receiver)?)
            }
        },
        ExpressionKind::EnumVariant {
            enumeration,
            variant,
        } => format!(
            "{}::{}",
            rust_type_identifier(enumeration),
            rust_type_identifier(variant)
        ),
        ExpressionKind::Binary {
            left,
            operator,
            right,
        } => {
            if *operator == BinaryOperator::Add && expression.ty == Type::String {
                format!(
                    "format!(\"{{}}{{}}\", {}, {})",
                    emit_borrow_source(left)?,
                    emit_borrow_source(right)?
                )
            } else {
                let precedence = binary_precedence(*operator);
                let output = format!(
                    "{} {} {}",
                    emit_expression_with_precedence(left, precedence)?,
                    emit_operator(*operator),
                    emit_expression_with_precedence(right, precedence + 1)?
                );
                if precedence < parent_precedence {
                    format!("({output})")
                } else {
                    output
                }
            }
        }
        ExpressionKind::Unary { operator, value } => {
            format!(
                "{}({})",
                emit_unary_operator(*operator),
                emit_expression(value)?
            )
        }
        ExpressionKind::Conditional {
            condition,
            then_value,
            else_value,
        } => format!(
            "if {} {{ {} }} else {{ {} }}",
            emit_expression(condition)?,
            emit_expression(then_value)?,
            emit_expression(else_value)?
        ),
        ExpressionKind::Template { parts, expressions } => {
            if parts.len() != expressions.len() + 1 {
                return Err(CodegenError::InvalidIr(
                    "template parts must surround every expression".to_owned(),
                ));
            }
            let format_string =
                parts
                    .iter()
                    .enumerate()
                    .fold(String::new(), |mut output, (index, part)| {
                        output.push_str(&part.replace('{', "{{").replace('}', "}}"));
                        if index < expressions.len() {
                            output.push_str("{}");
                        }
                        output
                    });
            if expressions.is_empty() {
                format!("{format_string:?}.to_string()")
            } else {
                format!(
                    "format!({format_string:?}, {})",
                    expressions
                        .iter()
                        .map(emit_borrow_source)
                        .collect::<Result<Vec<_>, _>>()?
                        .join(", ")
                )
            }
        }
    })
}

fn emit_operator(operator: BinaryOperator) -> &'static str {
    match operator {
        BinaryOperator::Add => "+",
        BinaryOperator::Subtract => "-",
        BinaryOperator::Multiply => "*",
        BinaryOperator::Divide => "/",
        BinaryOperator::Equal => "==",
        BinaryOperator::NotEqual => "!=",
        BinaryOperator::Greater => ">",
        BinaryOperator::GreaterEqual => ">=",
        BinaryOperator::Less => "<",
        BinaryOperator::LessEqual => "<=",
        BinaryOperator::And => "&&",
        BinaryOperator::Or => "||",
        BinaryOperator::Remainder => "%",
    }
}

fn binary_precedence(operator: BinaryOperator) -> u8 {
    match operator {
        BinaryOperator::Or => 1,
        BinaryOperator::And => 2,
        BinaryOperator::Equal | BinaryOperator::NotEqual => 3,
        BinaryOperator::Greater
        | BinaryOperator::GreaterEqual
        | BinaryOperator::Less
        | BinaryOperator::LessEqual => 4,
        BinaryOperator::Add | BinaryOperator::Subtract => 5,
        BinaryOperator::Multiply | BinaryOperator::Divide | BinaryOperator::Remainder => 6,
    }
}

fn emit_unary_operator(operator: UnaryOperator) -> &'static str {
    match operator {
        UnaryOperator::Not => "!",
        UnaryOperator::Negate => "-",
    }
}

fn rust_callee(name: &str) -> String {
    match name {
        "JSON.parse" => "rustify_runtime::json::parse".to_owned(),
        "JSON.stringify" => "rustify_runtime::json::stringify".to_owned(),
        "JSON.stringifyPretty" => "rustify_runtime::json::stringify_pretty".to_owned(),
        "Rustify.sleep" => "rustify_runtime::async_runtime::sleep".to_owned(),
        "Math.abs" => "f64::abs".to_owned(),
        "Math.floor" => "f64::floor".to_owned(),
        "Math.ceil" => "f64::ceil".to_owned(),
        "Math.round" => "f64::round".to_owned(),
        "Math.min" => "f64::min".to_owned(),
        "Math.max" => "f64::max".to_owned(),
        "Math.pow" => "f64::powf".to_owned(),
        "Ok" | "Err" => name.to_owned(),
        _ => rust_identifier(name),
    }
}

fn rust_identifier(name: &str) -> String {
    let mut output = String::new();
    for (index, character) in name.chars().enumerate() {
        if character.is_ascii_uppercase() {
            if index > 0 && !output.ends_with('_') {
                output.push('_');
            }
            output.push(character.to_ascii_lowercase());
        } else if character == '$' {
            output.push_str("_dollar_");
        } else {
            output.push(character);
        }
    }
    if matches!(
        output.as_str(),
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
    ) {
        format!("r#{output}")
    } else {
        output
    }
}

fn rust_type_identifier(name: &str) -> String {
    let mut output = String::new();
    let mut capitalize = true;

    for character in name.chars() {
        if character == '$' {
            output.push_str("Dollar");
            capitalize = true;
        } else if character == '_' {
            capitalize = true;
        } else if capitalize {
            output.extend(character.to_uppercase());
            capitalize = false;
        } else {
            output.push(character);
        }
    }

    if output == "Self" {
        "RustifySelf".to_owned()
    } else {
        output
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rustify_ir::{Function, Parameter};

    fn expression(ty: Type, kind: ExpressionKind) -> Expression {
        Expression { ty, kind }
    }

    #[test]
    fn emits_template_literal() {
        let program = Program {
            functions: vec![Function {
                name: "greet".to_owned(),
                is_async: false,
                params: vec![Parameter {
                    name: "name".to_owned(),
                    ty: Type::String,
                }],
                return_type: Type::String,
                body: vec![Statement::Return(expression(
                    Type::String,
                    ExpressionKind::Template {
                        parts: vec!["Hi ".to_owned(), String::new()],
                        expressions: vec![expression(
                            Type::String,
                            ExpressionKind::Identifier("name".to_owned()),
                        )],
                    },
                ))],
            }],
            ..Program::default()
        };
        assert!(emit(&program).unwrap().contains("format!(\"Hi {}\", name)"));
    }

    #[test]
    fn emits_control_flow_and_number_literals() {
        let condition = expression(
            Type::Bool,
            ExpressionKind::Binary {
                left: Box::new(expression(
                    Type::F64,
                    ExpressionKind::Identifier("value".to_owned()),
                )),
                operator: BinaryOperator::Greater,
                right: Box::new(expression(Type::F64, ExpressionKind::Number(0.0))),
            },
        );
        let program = Program {
            functions: vec![Function {
                name: "describe".to_owned(),
                is_async: false,
                params: vec![Parameter {
                    name: "value".to_owned(),
                    ty: Type::F64,
                }],
                return_type: Type::String,
                body: vec![Statement::If {
                    condition,
                    then_body: vec![],
                    else_body: vec![],
                }],
            }],
            ..Program::default()
        };
        assert!(emit(&program).unwrap().contains("if value > 0.0"));
    }

    #[test]
    fn emits_idiomatic_and_safe_rust_identifiers() {
        assert_eq!(rust_identifier("maybeName"), "maybe_name");
        assert_eq!(rust_identifier("firstName"), "first_name");
        assert_eq!(rust_identifier("type"), "r#type");
        assert_eq!(rust_type_identifier("user_record"), "UserRecord");
        assert_eq!(rust_type_identifier("$status"), "DollarStatus");
        assert_eq!(rust_type_identifier("Self"), "RustifySelf");
    }

    #[test]
    fn explains_rust_signatures_and_safe_collection_operations() {
        let program = Program {
            functions: vec![Function {
                name: "firstName".to_owned(),
                is_async: false,
                params: vec![Parameter {
                    name: "userNames".to_owned(),
                    ty: Type::Vec(Box::new(Type::String)),
                }],
                return_type: Type::Option(Box::new(Type::String)),
                body: vec![Statement::Return(Expression {
                    ty: Type::Option(Box::new(Type::String)),
                    kind: ExpressionKind::ArrayGet {
                        array: Box::new(Expression {
                            ty: Type::Vec(Box::new(Type::String)),
                            kind: ExpressionKind::Identifier("userNames".to_owned()),
                        }),
                        index: Box::new(Expression {
                            ty: Type::F64,
                            kind: ExpressionKind::Number(0.0),
                        }),
                    },
                })],
            }],
            ..Program::default()
        };
        let explanation = explain(&program);
        assert!(explanation.contains(
            "function firstName -> pub fn first_name(user_names: Vec<String>) -> Option<String>"
        ));
        assert!(
            explanation
                .contains("array[index] -> checked Vec::get(index).cloned() returning Option<T>")
        );
    }
}
