use rustify_ir::{Program, Type};
use std::fmt::Write;
use thiserror::Error;

#[derive(Debug, Error)]
pub enum CodegenError {
    #[error("unsupported expression in function body: {0}")]
    UnsupportedExpression(String),
    #[error("failed to format generated Rust: {0}")]
    Format(String),
}

pub fn emit(program: &Program) -> Result<String, CodegenError> {
    let mut output = String::from("// Generated by Rustify. Do not edit manually.\n\n");
    for structure in &program.structs {
        writeln!(output, "#[derive(Clone, Debug)]").unwrap();
        writeln!(output, "pub struct {} {{", structure.name).unwrap();
        for field in &structure.fields {
            writeln!(output, "    pub {}: {},", field.name, emit_type(&field.ty)).unwrap();
        }
        writeln!(output, "}}\n").unwrap();
    }
    for enumeration in &program.enums {
        writeln!(output, "#[derive(Clone, Debug, PartialEq)]").unwrap();
        writeln!(output, "pub enum {} {{", enumeration.name).unwrap();
        for variant in &enumeration.variants {
            writeln!(output, "    {variant},").unwrap();
        }
        writeln!(output, "}}\n").unwrap();
    }
    for function in &program.functions {
        write!(output, "pub fn {}(", function.name).unwrap();
        for (index, parameter) in function.params.iter().enumerate() {
            if index > 0 {
                output.push_str(", ");
            }
            write!(output, "{}: {}", parameter.name, emit_type(&parameter.ty)).unwrap();
        }
        writeln!(output, ") -> {} {{", emit_type(&function.return_type)).unwrap();
        for statement in split_statements(&function.body) {
            let emitted = emit_statement(statement)?;
            for line in emitted.lines() {
                writeln!(output, "    {line}").unwrap();
            }
        }
        writeln!(output, "}}\n").unwrap();
    }
    Ok(output)
}

pub fn emit_type(ty: &Type) -> String {
    match ty {
        Type::String => "String".to_owned(),
        Type::F64 => "f64".to_owned(),
        Type::Bool => "bool".to_owned(),
        Type::Unit => "()".to_owned(),
        Type::Named(name) => name.clone(),
        Type::Vec(inner) => format!("Vec<{}>", emit_type(inner)),
        Type::Option(inner) => format!("Option<{}>", emit_type(inner)),
    }
}

fn split_statements(body: &str) -> Vec<&str> {
    let mut statements = Vec::new();
    let mut start = 0;
    let mut depth = 0_i32;
    let mut quote = None;
    let mut escaped = false;
    for (index, character) in body.char_indices() {
        if let Some(active_quote) = quote {
            if escaped {
                escaped = false;
            } else if character == '\\' {
                escaped = true;
            } else if character == active_quote {
                quote = None;
            }
            continue;
        }
        match character {
            '\'' | '"' | '`' => quote = Some(character),
            '{' => depth += 1,
            '}' => depth -= 1,
            ';' | '\n' if depth == 0 => {
                if !body[start..index].trim().is_empty() {
                    statements.push(body[start..index].trim());
                }
                start = index + character.len_utf8();
            }
            _ => {}
        }
    }
    if !body[start..].trim().is_empty() {
        statements.push(body[start..].trim());
    }
    statements
}

fn emit_statement(statement: &str) -> Result<String, CodegenError> {
    let statement = statement.trim().trim_end_matches(';');
    if let Some(expression) = statement.strip_prefix("return ") {
        return Ok(format!("return {};", emit_expr(expression)?));
    }
    if let Some(rest) = statement.strip_prefix("const ") {
        return emit_variable(rest, false);
    }
    if let Some(rest) = statement.strip_prefix("let ") {
        return emit_variable(rest, true);
    }
    if let Some(args) = statement
        .strip_prefix("console.log(")
        .and_then(|value| value.strip_suffix(')'))
    {
        if args.trim_start().starts_with('`') {
            return Ok(format!("println!({});", emit_template(args)?));
        }
        return Ok(format!("println!(\"{{:?}}\", {});", emit_expr(args)?));
    }
    if statement.starts_with("if ")
        || statement.starts_with("while ")
        || statement.starts_with("for ")
    {
        return Ok(statement
            .replace("for (const ", "for ")
            .replace("for (let ", "for ")
            .replace(" of ", " in ")
            .replace(") {", " {"));
    }
    Ok(format!("{};", emit_expr(statement)?))
}

fn emit_variable(rest: &str, mutable: bool) -> Result<String, CodegenError> {
    let (left, right) = rest
        .split_once('=')
        .ok_or_else(|| CodegenError::UnsupportedExpression(rest.to_owned()))?;
    let name = left.split(':').next().unwrap_or(left).trim();
    Ok(format!(
        "let {}{} = {};",
        if mutable { "mut " } else { "" },
        name,
        emit_expr(right.trim())?
    ))
}

fn emit_expr(expression: &str) -> Result<String, CodegenError> {
    let expression = expression.trim();
    if expression.starts_with('`') && expression.ends_with('`') {
        return emit_template(expression);
    }
    if (expression.starts_with('"') && expression.ends_with('"'))
        || (expression.starts_with('\'') && expression.ends_with('\''))
    {
        let value = expression.trim_matches(['"', '\'']);
        return Ok(format!("{value:?}.to_string()"));
    }
    Ok(expression
        .replace("===", "==")
        .replace("!==", "!=")
        .replace(".length", ".len()"))
}

fn emit_template(template: &str) -> Result<String, CodegenError> {
    let content = template
        .strip_prefix('`')
        .and_then(|value| value.strip_suffix('`'))
        .ok_or_else(|| CodegenError::UnsupportedExpression(template.to_owned()))?;
    let mut format_string = String::new();
    let mut arguments = Vec::new();
    let mut remainder = content;
    while let Some(start) = remainder.find("${") {
        format_string.push_str(&remainder[..start].replace('{', "{{").replace('}', "}}"));
        let after_start = &remainder[start + 2..];
        let end = after_start
            .find('}')
            .ok_or_else(|| CodegenError::UnsupportedExpression(template.to_owned()))?;
        format_string.push_str("{}");
        arguments.push(after_start[..end].trim());
        remainder = &after_start[end + 1..];
    }
    format_string.push_str(&remainder.replace('{', "{{").replace('}', "}}"));
    if arguments.is_empty() {
        Ok(format!("{format_string:?}.to_string()"))
    } else {
        Ok(format!(
            "format!({format_string:?}, {})",
            arguments.join(", ")
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rustify_ir::{Function, Parameter};

    #[test]
    fn emits_template_literal() {
        let program = Program {
            functions: vec![Function {
                name: "greet".to_owned(),
                params: vec![Parameter {
                    name: "name".to_owned(),
                    ty: Type::String,
                }],
                return_type: Type::String,
                body: "return `Hi ${name}`".to_owned(),
            }],
            ..Program::default()
        };
        assert!(emit(&program).unwrap().contains("format!(\"Hi {}\", name)"));
    }
}
