// Generated by Rustify. Do not edit manually.

#[allow(dead_code, unused_imports)]
mod rustify_globals {
    pub const APP_NAME: &'static str = "RustifyGlobalDemo";

    pub const TIMEOUT_MS: f64 = 5000.0;

    pub const MAX_CONNECTIONS: f64 = 20.0;
}

#[allow(dead_code, unused_imports)]
mod rustify_main {

    pub fn run_demo() {
        println!(
            "{:?}",
            format!("{}{}", "Aplicación: ".to_string(), APP_NAME)
        );
        println!("{}", format!("Timeout: {}ms", TIMEOUT_MS));
        println!("{}", format!("Conexiones Máximas: {}", MAX_CONNECTIONS));
    }
}

pub use rustify_main::*;
